# Generated by the release workflow in woksin/reap. Do not edit by hand.
class Reap < Formula
  desc "Assess common stale developer and application data before pruning it"
  homepage "https://github.com/woksin/reap"
  version "3.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/woksin/reap/releases/download/v3.0.0/reap-macos-arm64.tar.gz"
      sha256 "460af8d6753b1644a705e9a6ce5dc267b31f0938100abf598ebd2ecf16bb640b"
    end
    on_intel do
      url "https://github.com/woksin/reap/releases/download/v3.0.0/reap-macos-x86_64.tar.gz"
      sha256 "a9727aad3d0aa675ad66c61afad67d4cd7778229b211302b6f2e0e337bac1598"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/woksin/reap/releases/download/v3.0.0/reap-linux-arm64.tar.gz"
      sha256 "eb7ab99f158f55cb2591e771804355bb461593176ff9a3f676efad79f8b9c2d8"
    end
    on_intel do
      url "https://github.com/woksin/reap/releases/download/v3.0.0/reap-linux-x86_64.tar.gz"
      sha256 "4acee394d9a2ea027264879a93a8b22e44da25ff58c9cd026ca9e94e1c0b5a9e"
    end
  end

  def install
    bin.install "reap"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/reap --version")
  end
end
